In [1]:
#path to the CORD-19 dataset
DATA_PATH = r"D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01"

METADATA_FILE = f"{DATA_PATH}/metadata.csv"

In [2]:
#print the list of files in the dataset directory
import os
print(os.listdir(DATA_PATH))

['arxiv', 'arxiv.tar.gz', 'biorxiv_medrxiv', 'biorxiv_medrxiv.tar.gz', 'changelog', 'comm_use_subset.tar.gz', 'cord_19_embeddings_5_1.tar.gz', 'custom_license.tar.gz', 'metadata.csv', 'noncomm_use_subset.tar.gz']

In [3]:
#print the list of all files in the dataset directory and its subdirectories
import os

for root, dirs, files in os.walk(DATA_PATH):
    for file in files:
        print(os.path.join(root, file))

D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv.tar.gz
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\biorxiv_medrxiv.tar.gz
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\changelog
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\comm_use_subset.tar.gz
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\cord_19_embeddings_5_1.tar.gz
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\custom_license.tar.gz
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\metadata.csv
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\noncomm_use_subset.tar.gz
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\003d2e515e1aaf06f0052769953e861ed8e56608.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\00a407540a8bdd6d7425bd8a561eb21d69682511.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\00c386ee8b9fac7eeb2291a72d52966d83eec814.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\024b30561568979f525d8b2580f85122c02008a0.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\02b3c0c87a6b32d5107a6e05f83f73cb7f939432.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\037fa0356fa70e796d34d6df6e4f5281cda1be6e.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\03cc61010171d8c71d4350f18d7c57e8b90cd5bb.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\03fe33ffc8d87e408f2e8411a624381efd8b66db.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\044de919f32956337edc04dd9dda8458c5d6a83d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\049ea432acc08b04a3e21c390f62be3d845a2e2c.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\04fc9f631e698a53691d96eaf89141354420539d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0512b8e6e26f790008d3dd7b48b6218b07af1fa1.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\067e53fab4bdec6e6dd07365d38f7e8b3be9c688.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0696d40a8c863f89203c524ee16a0006e2bf5148.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\06cad91161f09a9f28a5f07ecbd84edf3e7a87df.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0765596362e6b109eb040cd725aea94690cdafdf.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\07a60045768dfdb11e251513b1eeca679b93c0f1.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\07c7724815245c8855f3c3f4883870ffacb4ead2.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0846109754ca9d2d03984dbe702ca29b55f7ca49.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\08935ec8109d6356e843176a946afce672815e96.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0912c78de271b083438d1e7be51873aa959eca40.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0940e70d9d7ae49cab612c8f5c22957601152aa7.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0ab9404566ff5d8d81aebd0e9d9128b9589d9015.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0b70c1fd82bd1962ab7eec83bdc61fcdb9a2db56.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0cda048d50c1e093a9c5c6f126836a7e12a14eb7.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0ceca229cb2332c12a13e3b81f0369935a30bdb3.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0d90a077ea399c29a8b22105bd6a6bc61613579c.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0deef7e050171f0fb38e0d0733c9de67298891f7.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0e1451f1b7ecda5f1e941bf8a2ee4cdc0394c445.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0e2cb8e30cb7f94777dcd408097f0f85483561c8.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0e5b67b533af13d2f0b75e10754d1ae76e419e5c.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0e64903b318f69c36fa103399222f3e9c3b1ca89.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0e90220ead6de5039b83526fae0e6953d3051a10.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0f23d5716eca022036940aca5ca7eabcb2117f6b.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0f995b05821b58b02e914422b56fba615d0e8d7f.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0fa87c9b7907d9d0c6ca454e8b5f34d4cce78d41.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\0ff1d5f15854ee14f5a1739cc60c2d488d025b70.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\113e00e55679d3ad398acfba07ab35530d076154.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\117afd18d9c6dda005f3f22cef3b3bf023e2e45a.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1267c9e461b0f70ed1ce7c5f50989951d0b903e3.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\128b8a9d8f8ebcfe262356ea40808eb2517fefcd.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\128ebd160f9a5e799632a35440ce72534ede646b.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\129ff900ff8bc31ac5b9ee1b3768a57a6259f425.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1345c27caadfe883cbd68147767efcfc34207e8c.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1360b6c29928bc88e40f1820b6da4bd0efaa6e05.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\13e81a52ac2f1dbb059eeab61f739d979ae3412d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\143aa423e08cae3d9cdc2a5845a5cc39886fe0ce.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1491b1994a59738353532cc5faba1767f289e11b.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\152a62edb20b9cda73328d1ad305248a95ce999f.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\157975517d3dc3220a80a47e558b49d2755bbc6a.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\15c7e413de2e615378e1c0d4fa23d1f3425af285.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1601e9f2bbf89f04f967a4f5f49d7adeca7f0719.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\160bffa73923d95f7d62ba4e85e233cc7bdd2a4c.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\16c706d9f762555b985acdae97914d49e7b4ef1c.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\17a7bccd1d6f13d76838f88b379591cb75be20fd.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\184eb940b17bb8b2c9fbccd1f7ee2069627b8cea.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1887c838c0267559f70b4d5898f2bd4cd4ed8213.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\189f38311305a39224ad1a55b7da054056d64bf9.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\18d8d389f6effffd78ebf3c65f13f1241a6dd20d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1932ea139d08d1256a77ccdeeae510f6120ce6bf.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\19cf3796f2b87a2216d1134f7202ce83f9ccf63b.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1a0c55a139eb966fb19e72b5ca560487d3ff27fd.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1a102c54ce239b21b2b2ced7fb340c6c2d6c4917.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1a59ca238c64e4bae304240d7df787cf0345d50e.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1a854bfceb615249fd9c75f3f4491b0554e59c16.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1ab380fd0d283617d874127eee0f3b27e0f87ae5.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1b0ffeb0094fb5a60b103d0a8945e4311ea4041d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1b3ca29a04386d3d18f8b9cb83e2b2c14d4cd994.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1b6259770abfcb3ad924f0e8c138912c58aafca8.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1b94ee20e6cd598f5c44c1ad5b5ec0cad116e2a3.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1b9dd828ff1a7c4622f15049a5ce2617c056cede.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1bca8f0eae80a8e86c7e277413a6a0b067b3a04c.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1bd63fdfbecb372ca5861253e67ab9722d647d8e.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1bde8d09867997946c944745abbf6e8d7422583b.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1bf8d9e22061ae4ab5afd9902aafefc005495758.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1c47f04cd1e7a5ffa80df67872b379342ed9c6f4.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1c56023b04a6fa6cad58de4332fb7ce830e658c3.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1c5876f59b8eb7da373512c70a4fe8e113a0ed29.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1c588fca3c13303f444f545a5ad5318bdf5ff460.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1ccdbf2233cdec55a0166d97a13abf00af70cfe1.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1d93c5f7a7851227cc1aaf7ed0f4ee3aa72ac159.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1ed0667897d6fcba12babaac4e53430ab7a111d2.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1ed171376f8afb9d629b8f623c910947a1105e6e.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1f0072340bfb707caeebd129ecd30711841b613a.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1fa43de01deff122b935e7bb0677f82111ff867e.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1fb864c8c0904e7d26a68844735180f2b108196d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\1fc4da7de0646080e840e2b8cfe2c90c39c48f89.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\202153e9041429d60d6f1936a85a0a6947cdb43b.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\20694e3ba90fd8cea22a74338bc3c43fbe956256.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\20a9f2d1c437f46eb7a574064efe228fd36bbb0f.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\20c0ef920b43f54020a22dc54898380ead2d9cdf.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2190a91bcb4d72ca47b8d1414e7ea7b8ae743701.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\21b9d399fcf199b32c80ecaae8bb3cc1064e7bfb.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2242bb35993b5306fbc74b277db7ccbe6ebbed98.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\22edc9d8bb18253cdbb7905492c73387b4aee8c4.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\22f4589db7910d6e05162089c6e44a3d91471d7f.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2305deb2b01f516b57b37719a3c62804637a9139.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\23111e964de222a6ae1e70e5e69226beea57a6bb.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2318979bd91eaeb76e8521170d5456b955402e9f.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\23202067b68fabd242f610252e7813b2ef116710.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\238b1d30ab2a34817abf6b244d6ff4e84d1692d7.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\23a8045db90c6b6130dbe705c90d6ad7a4565a0b.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\23b1bc716257c6ab30fb3198d76cca3128715cc0.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\23f28ba5aa5ebfb8ef2ea936554d0676b74a2f5d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\24013cb9ca00107d170d03c4a9a20d9edc55cb47.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2439614328da116439f51ad2113eff15d76cd842.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\245eafba08bf568da3de70b7da528e6072700a9f.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\24894230a14d3607caea22bffcda1105bcfd09a3.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\24a8d61289ce1c542917b246a732649ef52d254b.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\267845c9ab6a1fda8688eb4bc20477e4305a7397.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\267d96cdf722030570e67225a1f83edeafa0352c.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\26ad5d7fbb87bc58c2784d00df9d16840a5954f3.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\26d11d2eab9b9842130e1fef2ce6f6e22324556d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\27152550d3e079c9151c9cadb07d21560a906701.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\27dc2cb28d6e04f52676371c65b7dc1de3e9e7d7.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\27fbd5dfa1e12e053571809eac75c63667c20d60.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2808a9a502685d036001e0b7dcccc4dbf2d52fc7.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\28277552ca17ff1db6ab660980eee1d19e95ea3d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2840d269703173ccf61b0fd31bf73c0300322a41.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\28aa8a08db150a020cca3eaed6755178c0fbc5c4.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\28ad1266569f30e5d37591c17d4155b5f38686a3.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2a065ae55861ccf695051ff72e3c0f45f6fbd350.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2ae5bf9843256379921ddd22603012106322f1f7.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2ae81644d62af97d80322750eaf154c025fe3ac8.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2bcc0b5598cfa52910f51d0d93b19c824076a860.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2bcda36d390006af3c02fc70d34528825872df92.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2bcf6e29fa69aa4a841667ab499c73c3700f9e22.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2c146cbd938e7d0e49e887dd06225c3f1443ecbf.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2c3a21d606c4168de8ad7dd5e5e89ef09a9cc214.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2c55a747d7e3d676fbedaaa5794c4d7b2923996f.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2c64394abb5e97b4efcb57c18e8e649b869a61bd.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2c837018d332088b3b45f0b6189d1df3cb53064d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2d40f76055a7c28dd30c8b8f60c31724f8991cd8.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2dbbd338a162539f945001a81e7ea3d1094ae436.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2df813945620a682a33f7aeb71a801a55a4d62f5.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2e31de7d7a946c9fda6a08e9a28c05ffcd725245.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2fa101b6cc29699f9909ee684de9b35ccfb6bc5b.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2faa58decdd46ce8808003cc53d0f98764d9acd6.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2fb2ebfbaf6dd3d259e918052bf49c8beda121e0.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2fbdb8d81f4cdb09780f1031ef50ca1efc32ec93.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2fc31624e5351b891085588733a2d01d4581a7ec.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\2fc5120658303eb9511016ddf9aa18e31b3d31a4.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\304a515db50dea49cc8127b885ba8f7ecba38861.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\309f789af580cd8118949f25277c0da525fb47c1.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\30bf8179a7859d1b72b82985e1f44b54f92d1f3d.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\30db9d6ae4237690af802342f3297b967d26ba24.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\322bd241d21b27b8a0bf4aaf96839d2843b87c20.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\32bf7ad3fdda71036b48f7dc85cad407674277b7.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\32e44618d02320b50abcfe2545488a26a80df432.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\3324f2015b89803fa67a6ee320989fcf848a6345.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\33476769fec9c469b65befcb4c0497c07ecf964f.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\3396640307309ecf8c776de4c7344d5b943e5282.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\33db9d032b967485d628f73408ebfb6953db40a7.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\3401218e753198b786af2e1fb5c15bb79a43ba53.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\3433860ec8cbe9ffaf8d8cf00addcd2adc839bfc.json
D:/code/Final Year Project/cord-19_2020-05-01/2020-05-01\arxiv\arxiv\pdf_json\34e105872c774ec5f4d8c06f0c1b80b370cdc111.json

In [4]:
#load the metadata CSV file into a pandas DataFrame and print its shape and column names
import pandas as pd

metadata_path = os.path.join(DATA_PATH, "metadata.csv")

df = pd.read_csv(metadata_path)

print(df.shape)
#print the column names of the DataFrame
print(df.columns.tolist())

(59887, 19)
['cord_uid', 'sha', 'source_x', 'title', 'doi', 'pmcid', 'pubmed_id', 'license', 'abstract', 'publish_time', 'authors', 'journal', 'Microsoft Academic Paper ID', 'WHO #Covidence', 'arxiv_id', 'has_pdf_parse', 'has_pmc_xml_parse', 'full_text_file', 'url']

C:\Users\anime\AppData\Local\Temp\ipykernel_624\654075006.py:6: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(metadata_path)

In [5]:
#print the first few rows of the DataFrame to get an overview of the data
print(df.head())

   cord_uid                                       sha source_x  \
0  zjufx4fo  b2897e1277f56641193a6db73825f707eed3e4c9      PMC
1  ymceytj3  e3d0d482ebd9a8ba81c254cc433f314142e72174      PMC
2  wzj2glte  00b1d99e70f779eb4ede50059db469c65e8c1469      PMC
3  2sfqsfm1  cf584e00f637cbd8f1bb35f3f09f5ed07b71aeb0      PMC
4  i0zym7iq  dde02f11923815e6a16a31dd6298c46b109c5dfa      PMC

                                               title  \
0  Sequence requirements for RNA strand transfer ...
1  Crystal structure of murine sCEACAM1a[1,4]: a ...
2  Synthesis of a novel hepatitis C virus protein...
3  Structure of coronavirus main proteinase revea...
4  Discontinuous and non-discontinuous subgenomic...

                        doi      pmcid   pubmed_id license  \
0  10.1093/emboj/20.24.7220  PMC125340  11742998.0     unk
1   10.1093/emboj/21.9.2076  PMC125375  11980704.0     unk
2  10.1093/emboj/20.14.3840  PMC125543  11447125.0   no-cc
3      10.1093/emboj/cdf327  PMC126080  12093723.0     unk
4      10.1093/emboj/cdf635  PMC136939  12456663.0     unk

                                            abstract publish_time  \
0  Nidovirus subgenomic mRNAs contain a leader se...   2001-12-17
1  CEACAM1 is a member of the carcinoembryonic an...   2002-05-01
2  Hepatitis C virus (HCV) is an important human ...   2001-07-16
3  The key enzyme in coronavirus polyprotein proc...   2002-07-01
4  Arteri-, corona-, toro- and roniviruses are ev...   2002-12-01

                                             authors           journal  \
0  Pasternak, Alexander O.; van den Born, Erwin; ...  The EMBO Journal
1  Tan, Kemin; Zelus, Bruce D.; Meijers, Rob; Liu...  The EMBO Journal
2  Xu, Zhenming; Choi, Jinah; Yen, T.S.Benedict; ...            EMBO J
3  Anand, Kanchan; Palm, Gottfried J.; Mesters, J...  The EMBO Journal
4  van Vliet, A.L.W.; Smits, S.L.; Rottier, P.J.M...  The EMBO Journal

   Microsoft Academic Paper ID WHO #Covidence arxiv_id  has_pdf_parse  \
0                          NaN            NaN      NaN           True
1                          NaN            NaN      NaN           True
2                          NaN            NaN      NaN           True
3                          NaN            NaN      NaN           True
4                          NaN            NaN      NaN           True

   has_pmc_xml_parse  full_text_file  \
0               True  custom_license
1               True  custom_license
2               True  custom_license
3               True  custom_license
4               True  custom_license

                                                 url
0  http://europepmc.org/articles/pmc125340?pdf=re...
1  http://europepmc.org/articles/pmc125375?pdf=re...
2  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...
3  http://europepmc.org/articles/pmc126080?pdf=re...
4  http://europepmc.org/articles/pmc136939?pdf=re...

In [6]:
#check if the metadata directory exists
metadata_path = os.path.join(DATA_PATH, "metadata")

#print whether the metadata directory exists
print(os.path.exists(metadata_path))

False

In [7]:
#print the column names of the DataFrame
print(df.columns.tolist())

['cord_uid', 'sha', 'source_x', 'title', 'doi', 'pmcid', 'pubmed_id', 'license', 'abstract', 'publish_time', 'authors', 'journal', 'Microsoft Academic Paper ID', 'WHO #Covidence', 'arxiv_id', 'has_pdf_parse', 'has_pmc_xml_parse', 'full_text_file', 'url']

In [8]:
#print only the title and abstract columns of the DataFrame from the first few rows to get an overview of the data
print(df[['title','abstract']].head())

                                               title  \
0  Sequence requirements for RNA strand transfer ...
1  Crystal structure of murine sCEACAM1a[1,4]: a ...
2  Synthesis of a novel hepatitis C virus protein...
3  Structure of coronavirus main proteinase revea...
4  Discontinuous and non-discontinuous subgenomic...

                                            abstract
0  Nidovirus subgenomic mRNAs contain a leader se...
1  CEACAM1 is a member of the carcinoembryonic an...
2  Hepatitis C virus (HCV) is an important human ...
3  The key enzyme in coronavirus polyprotein proc...
4  Arteri-, corona-, toro- and roniviruses are ev...

In [9]:
#select only the title and abstract columns and create a copy of the DataFrame which will be used for further processing
dataset = df[['title','abstract']].copy()

In [10]:
#rename the columns of the DataFrame to "input" and "output" for further processing
dataset = dataset.rename(columns={
    "abstract":"input",
    "title":"output"
})

In [11]:
# Remove missing values 
dataset = dataset.dropna(subset=["input", "output"])

# Remove empty values from the dataset by filtering out rows where either the "input" or "output" column is empty or contains only whitespace
dataset = dataset[
    (dataset["input"].str.strip() != "") &
    (dataset["output"].str.strip() != "")
]

# Check result of the cleaning process by printing the shape of the dataset and the first few rows
print("Dataset shape:", dataset.shape)
#print the first few rows of the cleaned dataset to verify that the cleaning process was successful
print(dataset.head())

Dataset shape: (48603, 2)
                                              output  \
0  Sequence requirements for RNA strand transfer ...
1  Crystal structure of murine sCEACAM1a[1,4]: a ...
2  Synthesis of a novel hepatitis C virus protein...
3  Structure of coronavirus main proteinase revea...
4  Discontinuous and non-discontinuous subgenomic...

                                               input
0  Nidovirus subgenomic mRNAs contain a leader se...
1  CEACAM1 is a member of the carcinoembryonic an...
2  Hepatitis C virus (HCV) is an important human ...
3  The key enzyme in coronavirus polyprotein proc...
4  Arteri-, corona-, toro- and roniviruses are ev...

In [12]:
# Install scikit-learn of not already installed
#!pip install scikit-learn

In [13]:
from sklearn.model_selection import train_test_split

# First: 80% training, 20% temporary
train_data, temp_data = train_test_split(
    dataset,
    test_size=0.20,
    random_state=42
)

# Second: split temporary 20% into 10% validation and 10% test
validation_data, test_data = train_test_split(
    temp_data,
    test_size=0.50,
    random_state=42
)

#print the shapes of the training, validation, and test datasets to verify the splits
print("Training:", train_data.shape)
print("Validation:", validation_data.shape)
print("Test:", test_data.shape)

Training: (38882, 2)
Validation: (4860, 2)
Test: (4861, 2)

In [14]:
#install the required libraries for the project if not already installed
#!pip install -q transformers datasets sentencepiece accelerate

In [15]:
#import datasets library to create Hugging Face datasets from pandas DataFrames
from datasets import Dataset

#create hugging face datasets from the pandas DataFrames for traning
train_dataset = Dataset.from_pandas(
    train_data[["input", "output"]].reset_index(drop=True)
)

#create hugging face datasets from the pandas DataFrames for validation
validation_dataset = Dataset.from_pandas(
    validation_data[["input", "output"]].reset_index(drop=True)
)

#create hugging face datasets from the pandas DataFrames for testing
test_dataset = Dataset.from_pandas(
    test_data[["input", "output"]].reset_index(drop=True)
)

#print the training, validation, and test datasets to verify their contents
print(train_dataset)
print(validation_dataset)
print(test_dataset)

C:\Users\anime\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Dataset({
    features: ['input', 'output'],
    num_rows: 38882
})
Dataset({
    features: ['input', 'output'],
    num_rows: 4860
})
Dataset({
    features: ['input', 'output'],
    num_rows: 4861
})

In [16]:
#load 
from transformers import BartTokenizer

tokenizer = BartTokenizer.from_pretrained(
    "facebook/bart-base"
)

print("Tokenizer loaded successfully")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Tokenizer loaded successfully

In [17]:
def tokenize_data(batch):

    # Tokenize input (abstract)
    inputs = tokenizer(
        batch["input"],
        max_length=384,
        truncation=True
    )

    # Tokenize output (title)
    targets = tokenizer(
        text_target=batch["output"],
        max_length=64,
        truncation=True
    )

    # Store title tokens as labels
    inputs["labels"] = targets["input_ids"]

    return inputs

In [ ]:
#create tokenized datasets for training, validation, and testing by applying the tokenize_data function to each dataset
tokenized_train = train_dataset.map(
    tokenize_data,
    batched=True,
    remove_columns=["input", "output"]
)

tokenized_validation = validation_dataset.map(
    tokenize_data,
    batched=True,
    remove_columns=["input", "output"]
)

tokenized_test = test_dataset.map(
    tokenize_data,
    batched=True,
    remove_columns=["input", "output"]
)

Map: 100%|██████████| 38882/38882 [00:07<00:00, 5242.81 examples/s]
Map: 100%|██████████| 4860/4860 [00:00<00:00, 5189.76 examples/s]
Map: 100%|██████████| 4861/4861 [00:01<00:00, 4404.20 examples/s]

In [19]:
print(tokenized_train)
print(tokenized_validation)
print(tokenized_test)

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 38882
})
Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 4860
})
Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 4861
})

In [20]:
import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU memory:",
          round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
          "GB")

PyTorch version: 2.11.0+cu128
GPU available: True
GPU: NVIDIA GeForce RTX 2050
GPU memory: 4.0 GB

In [21]:
#load the DataCollatorForSeq2Seq class from the transformers library to load the model and prepare the data for training
from transformers import DataCollatorForSeq2Seq

#create a data collator for sequence-to-sequence tasks using the BART tokenizer and model, with label padding token ID set to -100
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model="facebook/bart-base", #comment: specify the pre-trained BART model
    label_pad_token_id=-100 #comment: -100 is used to ignore the padding tokens in the loss calculation during training
)

print("Data collator ready")

Data collator ready

In [22]:
#print the number of input and output tokens for the first example in the training dataset
print("Input tokens:", len(tokenized_train[0]["input_ids"]))
print("Output tokens:", len(tokenized_train[0]["labels"]))

Input tokens: 200
Output tokens: 19

In [23]:
#load the BART model for conditional generation
from transformers import BartForConditionalGeneration

model = BartForConditionalGeneration.from_pretrained(
    "facebook/bart-base"
)

model.config.use_cache = False

print("BART-base loaded successfully")

Loading weights: 100%|██████████| 259/259 [00:00<00:00, 3369.93it/s]

BART-base loaded successfully

In [24]:
#create a Seq2SeqTrainer for testing the model with small dataset and limited steps
from transformers import Seq2SeqTrainingArguments

test_args = Seq2SeqTrainingArguments(
    output_dir="./bart-test",

    # Small batch for RTX 2050 4 GB
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,

    # Gradient accumulation
    gradient_accumulation_steps=4,

    # Only 20 steps for testing
    max_steps=20,

    # Learning rate
    learning_rate=5e-5,

    # Use GPU efficiently
    fp16=True,

    # Reduce GPU memory usage
    gradient_checkpointing=True,

    # Logging
    logging_steps=1,

    # No evaluation during this small test
    eval_strategy="no",

    # Don't save during test
    save_strategy="no",

    # No external logging
    report_to="none",

    # Optimizer
    optim="adamw_torch",

    # Generation settings
    predict_with_generate=False
)

print("Test training settings ready")

Test training settings ready

In [25]:
# Select a small subset of the training and validation datasets for testing 
small_train = tokenized_train.select(range(100))
small_validation = tokenized_validation.select(range(20))

#print the number of training and validation samples in the small datasets for testing
print("Training test samples:", len(small_train))
print("Validation test samples:", len(small_validation))

Training test samples: 100
Validation test samples: 20

In [26]:
#create a Seq2SeqTrainer for testing the model with small dataset and limited steps
from transformers import Seq2SeqTrainer

test_trainer = Seq2SeqTrainer(
    model=model,
    args=test_args,

    train_dataset=small_train,
    eval_dataset=small_validation,

    processing_class=tokenizer,
    data_collator=data_collator
)

print("Test Trainer created successfully")

Test Trainer created successfully

In [27]:
#train the model for a few steps to check if everything is working
test_trainer.train()

TrainOutput(global_step=20, training_loss=12.672259378433228, metrics={'train_runtime': 13.6256, 'train_samples_per_second': 5.871, 'train_steps_per_second': 1.468, 'total_flos': 13515427860480.0, 'train_loss': 12.672259378433228, 'epoch': 0.8})

In [28]:
#clear the test training data from the memory
import gc
import torch

del test_trainer
gc.collect()
torch.cuda.empty_cache()

print("GPU memory cleared")

GPU memory cleared

In [29]:
#create a real traning settings for the BART model using Seq2SeqTrainingArguments from the transformers library. 
#The training settings include output directory, batch sizes, gradient accumulation steps, number of epochs, learning rate, mixed precision training, gradient checkpointing, logging and evaluation strategies, saving strategies, optimizer choice, and generation settings.
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="./bart-cord19-results",

    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,

    gradient_accumulation_steps=8,

    num_train_epochs=1, #taning for 1 epoch to avoid overfitting and reduce training time

    learning_rate=5e-5,

    fp16=True,

    gradient_checkpointing=True,

    logging_steps=100,

    eval_strategy="steps",
    eval_steps=1000,

    save_strategy="steps",
    save_steps=1000,
    save_total_limit=2,

    load_best_model_at_end=True,

    report_to="none",

    optim="adamw_torch",

    predict_with_generate=False
)

print("Full training settings ready")

Full training settings ready

In [30]:
#create a real tranning settings for the BART model using Seq2SeqTrainer from the transformers library.
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,

    train_dataset=tokenized_train,
    eval_dataset=tokenized_validation,

    processing_class=tokenizer,
    data_collator=data_collator
)

print("Full Trainer created successfully")

Full Trainer created successfully

In [31]:
# Print GPU information and verify that the GPU is available for training
import torch

print("GPU:", torch.cuda.get_device_name(0))
print("GPU memory:",
      round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
      "GB")

GPU: NVIDIA GeForce RTX 2050
GPU memory: 4.0 GB

In [32]:
#train the BART model on the CORD-19 dataset using the Seq2SeqTrainer with the specified training settings and data collator
trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.47s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.90s/it]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s]
[transformers] There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

TrainOutput(global_step=4861, training_loss=17.282668122536997, metrics={'train_runtime': 6716.269, 'train_samples_per_second': 5.789, 'train_steps_per_second': 0.724, 'total_flos': 6217328444221440.0, 'train_loss': 17.282668122536997, 'epoch': 1.0})

In [ ]:
#save the trained BART model and tokenizer to the specified directory for future use
model_save_path = r"D:\code\Final Year Project\BART_MODEL\bart-cord19-final"

#save the trained BART model
trainer.save_model(model_save_path)

#save the trained BART tokenizer
tokenizer.save_pretrained(model_save_path)

print("Model saved successfully!")
print("Location:", model_save_path)

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.65s/it]

Model saved successfully!
Location: D:\code\Final Year Project\BART_MODEL\bart-cord19-final

In [35]:
#lets confirm the number of test samples in the tokenized test dataset
print("Test samples:", len(tokenized_test))

Test samples: 4861

In [36]:
#predict_with_generate is set to False, which means that the model will not generate predictions during evaluation. This is useful for tasks where you want to evaluate the model's performance without generating new sequences, such as when calculating metrics like accuracy or loss on a validation set.
predict_with_generate=False

In [ ]:
#set predict_with_generate to True to enable prediction generation during evaluation
training_args.predict_with_generate = True

In [ ]:
#print whether generation is enabled during evaluation based on the value of training_args.predict_with_generate
print("Generation enabled:",
      training_args.predict_with_generate)

Generation enabled: True

In [39]:
test_results = trainer.predict(
    tokenized_test,
    max_length=64,
    num_beams=4
)

print("Prediction completed!")

Prediction completed!

In [41]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = model.to(device)
model.eval()

print("Device:", device)
print("Model ready for generation")

Device: cuda
Model ready for generation

In [43]:
import torch
from transformers import BartForConditionalGeneration, BartTokenizer

model_path = r"D:\code\Final Year Project\BART_MODEL\bart-cord19-final"

tokenizer = BartTokenizer.from_pretrained(model_path)

model = BartForConditionalGeneration.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = model.to(device)
model.eval()

print("Model loaded successfully!")
print("Device:", device)
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

Loading weights: 100%|██████████| 260/260 [00:00<00:00, 3112.29it/s]

Model loaded successfully!
Device: cuda
GPU: NVIDIA GeForce RTX 2050

In [44]:
print("Test samples:", len(tokenized_test))
print("Columns:", tokenized_test.column_names)

Test samples: 4861
Columns: ['input_ids', 'attention_mask', 'labels']

In [47]:
import torch

predicted_titles = []

batch_size = 2

model.eval()

for i in range(0, len(tokenized_test), batch_size):

    batch = tokenized_test[i:i + batch_size]

    # Automatically pad different length inputs
    inputs = tokenizer.pad(
        {
            "input_ids": batch["input_ids"],
            "attention_mask": batch["attention_mask"]
        },
        padding=True,
        return_tensors="pt"
    )

    input_ids = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)

    # Generate summaries/titles
    with torch.no_grad():

        generated_ids = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=64,
            num_beams=2,
            early_stopping=True
        )

    # Convert generated tokens to text
    titles = tokenizer.batch_decode(
        generated_ids,
        skip_special_tokens=True
    )

    predicted_titles.extend(titles)

    # Progress
    if (i + batch_size) % 200 == 0 or i + batch_size >= len(tokenized_test):
        print(
            "Processed:",
            min(i + batch_size, len(tokenized_test)),
            "/",
            len(tokenized_test)
        )

print("\nGeneration completed!")
print("Total predictions:", len(predicted_titles))

Processed: 200 / 4861
Processed: 400 / 4861
Processed: 600 / 4861
Processed: 800 / 4861
Processed: 1000 / 4861
Processed: 1200 / 4861
Processed: 1400 / 4861
Processed: 1600 / 4861
Processed: 1800 / 4861
Processed: 2000 / 4861
Processed: 2200 / 4861
Processed: 2400 / 4861
Processed: 2600 / 4861
Processed: 2800 / 4861
Processed: 3000 / 4861
Processed: 3200 / 4861
Processed: 3400 / 4861
Processed: 3600 / 4861
Processed: 3800 / 4861
Processed: 4000 / 4861
Processed: 4200 / 4861
Processed: 4400 / 4861
Processed: 4600 / 4861
Processed: 4800 / 4861
Processed: 4861 / 4861

Generation completed!
Total predictions: 4861

In [49]:
labels = tokenized_test["labels"]

actual_titles = []

for label in labels:

    label = [
        token if token != -100
        else tokenizer.pad_token_id
        for token in label
    ]

    title = tokenizer.decode(
        label,
        skip_special_tokens=True
    )

    actual_titles.append(title)

print("Total actual titles:", len(actual_titles))

Total actual titles: 4861

In [50]:
for i in range(10):

    print("=" * 70)
    print("Example", i + 1)

    print("\nACTUAL TITLE:")
    print(actual_titles[i])

    print("\nGENERATED TITLE:")
    print(predicted_titles[i])

======================================================================
Example 1

ACTUAL TITLE:
Sows infected in pregnancy with porcine respiratory coronavirus show no evidence of protecting their sucking piglets against transmissible gastroenteritis

GENERATED TITLE:
Porcine respiratory coronavirus infection in suckled piglets
======================================================================
Example 2

ACTUAL TITLE:
A Point Mutation within the Replicase Gene Differentially Affects Coronavirus Genome versus Minigenome Replication

GENERATED TITLE:
Point Mutations at Nucleotide 637 Are Required for Minigenome Rescue in Transmissible Gastroenteritis Virus
======================================================================
Example 3

ACTUAL TITLE:
Diagnosis and Management of Community-Acquired Pneumonia: Evidence-Based Practice

GENERATED TITLE:
Community-Acquired Pneumonia in Adults for Nurse Practitioners
======================================================================
Example 4

ACTUAL TITLE:
Molecular analysis of sarcoidosis lymph nodes for microorganisms: a case–control study with clinical correlates

GENERATED TITLE:
Bacterial DNA in sarcoidosis mediastinal lymph nodes compared with control lymph nodes
======================================================================
Example 5

ACTUAL TITLE:
Feasibility of Controlling COVID-19 Outbreaks in the UK by Rolling Interventions

GENERATED TITLE:
Impact of suppression, suppression and multiple rolling interventions on the number and distribution of infections, growth of deaths, peaks and lengths of COVID-19 outbreaks in London and the UK
======================================================================
Example 6

ACTUAL TITLE:
Chapter 12 Early Warning Practice Using Internet-Based Data

GENERATED TITLE:
Early detection of infectious diseases using Internet-based data
======================================================================
Example 7

ACTUAL TITLE:
Multi-Organ Lesions in Suckling Mice Infected with SARS-Associated Mammalian Reovirus Linked with Apoptosis Induced by Viral Proteins μ1 and σ1

GENERATED TITLE:
Pathogenesis of a Novel mammalian reassortant reovirus BYD1 in suckling mice
======================================================================
Example 8

ACTUAL TITLE:
Peptide Vaccine: Progress and Challenges

GENERATED TITLE:
Peptide Vaccines
======================================================================
Example 9

ACTUAL TITLE:
Immune responses to RNA-virus infections of the CNS

GENERATED TITLE:
Immune Responses in the Central Nervous System
======================================================================
Example 10

ACTUAL TITLE:
Decontamination of rooms, medical equipment and ambulances using an aerosol of hydrogen peroxide disinfectant

GENERATED TITLE:
A dry fume of hydrogen peroxide disinfectant for decontamination of rooms, ambulances and different types of medical equipment

In [52]:
!pip install -q evaluate rouge_score

WARNING: You are using pip version 21.2.3; however, version 26.2.1 is available.
You should consider upgrading via the 'C:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.

In [54]:
import evaluate

rouge = evaluate.load("rouge")

print("ROUGE loaded successfully!")

ROUGE loaded successfully!

In [55]:
rouge_results = rouge.compute(
    predictions=predicted_titles,
    references=actual_titles,
    use_stemmer=True
)

print("ROUGE-1:", rouge_results["rouge1"])
print("ROUGE-2:", rouge_results["rouge2"])
print("ROUGE-L:", rouge_results["rougeL"])

ROUGE-1: 0.4454679422637692
ROUGE-2: 0.24077738388442266
ROUGE-L: 0.3899496369385822

In [56]:
rouge_1 = rouge_results["rouge1"] * 100
rouge_2 = rouge_results["rouge2"] * 100
rouge_l = rouge_results["rougeL"] * 100

print(f"ROUGE-1: {rouge_1:.2f}%")
print(f"ROUGE-2: {rouge_2:.2f}%")
print(f"ROUGE-L: {rouge_l:.2f}%")

ROUGE-1: 44.55%
ROUGE-2: 24.08%
ROUGE-L: 38.99%

In [57]:
import pandas as pd

rouge_table = pd.DataFrame({
    "Metric": [
        "ROUGE-1",
        "ROUGE-2",
        "ROUGE-L"
    ],

    "Score": [
        rouge_results["rouge1"],
        rouge_results["rouge2"],
        rouge_results["rougeL"]
    ],

    "Percentage": [
        rouge_results["rouge1"] * 100,
        rouge_results["rouge2"] * 100,
        rouge_results["rougeL"] * 100
    ]
})

rouge_table["Percentage"] = rouge_table["Percentage"].round(2)

print(rouge_table)

    Metric     Score  Percentage
0  ROUGE-1  0.445468       44.55
1  ROUGE-2  0.240777       24.08
2  ROUGE-L  0.389950       38.99

In [58]:
results_df = pd.DataFrame({
    "input": test_data["input"].values,
    "actual_title": actual_titles,
    "generated_title": predicted_titles
})

results_path = r"D:\code\Final Year Project\BART_MODEL\bart_predictions.csv"

results_df.to_csv(
    results_path,
    index=False
)

print("Predictions saved successfully!")
print("Location:", results_path)

Predictions saved successfully!
Location: D:\code\Final Year Project\BART_MODEL\bart_predictions.csv

In [59]:
rouge_path = r"D:\code\Final Year Project\BART_MODEL\rouge_results.csv"

rouge_table.to_csv(
    rouge_path,
    index=False
)

print("ROUGE results saved!")
print("Location:", rouge_path)

ROUGE results saved!
Location: D:\code\Final Year Project\BART_MODEL\rouge_results.csv

In [1]:
model_save_path = r"D:\code\Final Year Project\BART_MODEL\bart-cord19-final"

model.save_pretrained(model_save_path)
tokenizer.save_pretrained(model_save_path)

print("Final BART model saved successfully!")

NameError: name 'model' is not defined

In [2]:
from transformers import BartForConditionalGeneration, BartTokenizer
import torch

# Path of your trained model
model_path = r"D:\code\Final Year Project\BART_MODEL\bart-cord19-final"

# Load tokenizer
tokenizer = BartTokenizer.from_pretrained(model_path)

# Load trained BART model
model = BartForConditionalGeneration.from_pretrained(model_path)

# Use GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = model.to(device)
model.eval()

print("Model loaded successfully!")
print("Device:", device)

C:\Users\anime\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 260/260 [00:00<00:00, 1505.27it/s]

Model loaded successfully!
Device: cuda

In [3]:
def generate_title(input_text):
    
    # Tokenize input
    inputs = tokenizer(
        input_text,
        max_length=512,
        truncation=True,
        padding=True,
        return_tensors="pt"
    )

    # Move input to GPU/CPU
    input_ids = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)

    # Generate title
    with torch.no_grad():
        output_ids = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=64,
            num_beams=4,
            early_stopping=True,
            no_repeat_ngram_size=2
        )

    # Convert tokens to text
    title = tokenizer.decode(
        output_ids[0],
        skip_special_tokens=True
    )

    return title

In [ ]:
input_text = """
FACT SHEET FOR PATIENTS, PARENTS, AND CAREGIVERS
EMERGENCY USE AUTHORIZATION (EUA) OF PAXLOVID
FOR CORONAVIRUS DISEASE 2019 (COVID-19)
You are being given this Fact Sheet because your healthcare provider believes it is
necessary to provide you with PAXLOVID for the treatment of mild-to-moderate
coronavirus disease (COVID-19) caused by the SARS-CoV-2 virus. This Fact Sheet
contains information to help you understand the risks and benefits of taking the
PAXLOVID you may receive. This Fact Sheet also contains information about how to
take PAXLOVID and how to report side effects or problems with the appearance or
packaging of PAXLOVID.
The U.S. Food and Drug Administration (FDA) has issued an Emergency Use
Authorization (EUA) to make PAXLOVID available for the treatment of mild-to-moderate
COVID-19 in children 12 years of age and older weighing at least 88 pounds (40 kg)
who are at high risk for progression to severe COVID-19, including hospitalization or
death (for more details about an EUA please see “What is an Emergency Use
Authorization?” at the end of this document). Read this Fact Sheet for information
about PAXLOVID. Talk to your healthcare provider about your options or if you have
any questions. It is your choice to take PAXLOVID.
What is COVID-19?
COVID-19 is caused by a virus called a coronavirus. You can get COVID-19 through
close contact with another person who has the virus.
COVID-19 illnesses have ranged from very mild to severe, including illness resulting in
death. While information so far suggests that most COVID-19 illness is mild, serious
illness can happen and may cause some of your other medical conditions to become
worse. Older people and people of all ages with severe, long lasting (chronic) medical
conditions like heart disease, lung disease, and diabetes, for example seem to be at
higher risk of being hospitalized for COVID-19.
What is PAXLOVID?
PAXLOVID is a medicine that is available under EUA for the treatment of
mild-to-moderate COVID-19 in children 12 years of age and older weighing at least 88
pounds (40 kg) who are at high risk for progression to severe COVID-19, including
hospitalization or death.
PAXLOVID is FDA-approved for the treatment of COVID-19 in certain adults (see
section What other treatment choices are there?).
PAXLOVID is not FDA-approved or available under EUA for use in children younger
than 12 years of age or weighing less than 88 pounds (40 kg).
There is limited information about the safety and effectiveness of using PAXLOVID to
treat children younger than 12 years of age or weighing less than 88 pounds (40 kg)
with mild-to-moderate COVID-19.
2 Revised: 02/2026
What is the most important information I should know about PAXLOVID?
PAXLOVID can interact with other medicines causing severe or life-threatening side
effects or death. It is important to know the medicines that should not be taken with
PAXLOVID. """
title = generate_title(input_text)

print("INPUT:")
print(input_text)

print("\nGENERATED TITLE:")
print(title)

INPUT:

Background: After admission to hospital, COVID-19 progresses in a substantial proportion of patients to critical disease that requires intensive care unit (ICU) admission.

Methods: In a pragmatic, non-blinded trial, 387 patients aged 40-90 years were randomised to receive treatment with SoC plus doxycycline (n = 192) or SoC only (n = 195). The primary outcome was the need for ICU admission as judged by the attending physicians. Three types of analyses were carried out for the primary outcome: "Intention to treat" (ITT) based on randomisation; "Per protocol" (PP), excluding patients not treated according to randomisation; and "As treated" (AT), based on actual treatment received. The trial was undertaken in six hospitals in India with high-quality ICU facilities. An online application serving as the electronic case report form was developed to enable screening, randomisation and collection of outcomes data.

Results: Adherence to treatment per protocol was 95.1%. Among all 387 participants, 77 (19.9%) developed critical disease needing ICU admission. In all three primary outcome analyses, doxycycline was associated with a relative risk reduction (RRR) and absolute risk reduction (ARR): ITT 31.6% RRR, 7.4% ARR (P = 0.063); PP 40.7% RRR, 9.6% ARR (P = 0.017); AT 43.2% RRR, 10.8% ARR (P = 0.007), with numbers needed to treat (NTT) of 13.4 (ITT), 10.4 (PP), and 9.3 (AT), respectively. Doxycycline was well tolerated with not a single patient stopping treatment due to adverse events.

Conclusions: In hospitalized COVID-19 patients, doxycycline, a safe, inexpensive, and widely available antibiotic with anti-inflammatory properties, reduces the need for ICU admission when added to SoC.

Copyright: © 2023 Dhar et al. This is an open access article distributed under the terms of the Creative Commons Attribution License, which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.


GENERATED TITLE:
Doxycycline reduces the need for ICU admission in hospitalized COVID-19 patients